version: '3.1'

services:
  tomy_pg:
    image: postgres:15.1
    container_name: tomy_pg
    restart: always
    environment:
      POSTGRES_DB: tomydb
      POSTGRES_USER: utomy
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432
